sudo: true

language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m

before_install:
  - buildscripts/make_dependencies.sh # build protoc into /tmp/protobuf

os:
  - linux

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
